
2019-10-15 16:39:36,622 INFO: errors [in D:\Python practices\Udacity-Classdemo\fyyur\app.py:560]
2019-10-15 16:39:53,051 ERROR: Exception on /venues/create [GET] [in D:\Program Files\Python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Python practices\Udacity-Classdemo\fyyur\app.py", line 245, in create_venue_form
    form = VenueForm()
  File "D:\Program Files\Python37\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\flask_wtf\form.py", line 158, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "D:\Program Files\Python37\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "D:\Program Files\Python37\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "D:\Program Files\Python37\lib\site-packages\flask_wtf\csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "D:\Program Files\Python37\lib\site-packages\flask_wtf\csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
